app:
  name: "research_and_answer"
  version: "1.0.0"

database:
  type: sqlite
  path: "./medallion.db"

providers:
  ollama:
    base_url: "http://localhost:11434"
    timeout: 30s
    model: "llama3.1"
  openai:
    api_key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    timeout: 30s
    model: "gpt-3.5-turbo"

logging:
  level: info
  format: json

workflows:
  default: "workflows/workflow.yaml"
  
agents:
  default_provider: "ollama"
  
tools:
  web_search:
    enabled: true
    provider: "duckduckgo"
  document_retrieval:
    enabled: true
    provider: "sqlite"
  data_analysis:
    enabled: true
  pattern_recognition:
    enabled: true
  text_formatting:
    enabled: true
  citation_manager:
    enabled: true
  fact_checker:
    enabled: true
  quality_assessor:
    enabled: true
