name: research_and_answer
description: "Research and answer workflow that plans, researches, analyzes, writes, and reviews answers to questions"
agents:
  - planner
  - researcher
  - analyzer
  - writer
  - reviewer
steps:
  - name: plan
    agent: planner
    input: "{{.question}}"
    success_when: "contains_plan"
    
  - name: research
    agent: researcher
    depends_on: [plan]
    input: "Research the following plan: {{.plan.output}}"
    success_when: "has_sources"
    
  - name: analyze
    agent: analyzer
    depends_on: [research]
    input: "Analyze the research findings: {{.research.output}}"
    success_when: "has_analysis"
    
  - name: write
    agent: writer
    depends_on: [analyze]
    input: "Write a comprehensive answer based on: {{.analyze.output}}"
    success_when: "is_complete"
    
  - name: review
    agent: reviewer
    depends_on: [write]
    input: "Review and improve this answer: {{.write.output}}"
    success_when: "is_approved"
